### ISSUE TITLE
Catalog usage of non-OHM data

### ISSUE THREAD

**Issue by gregallensworth** [Open-Historical-Map-Labs/openhistoricaltiles#11]
Per discussion today, we should document what non-OHM data are being used, in preparation for potentially removing it. Off the cuff, this would seem to include NaturalEarth data (water bodies at large scale, per #7 ) and vanilla OSM data (some of the data-prep steps at https://github.com/OpenHistoricalMap/openmaptiles/).

**Comment by gregallensworth** [comment]
## water

### NaturalEarth

NaturalEarth data are used **exclusively** (no OSM) *through z5* to display water at large scales:
* `ne_110m_ocean`
* `ne_110m_lakes`
* `ne_50m_ocean`
* `ne_50m_lakes`
* `ne_10m_ocean`
* `ne_10m_lakes`

At *z6 exactly* the `ne_10m_ocean` is used to provide ocean/coastline content, and all other water comes from OSM/OHM.

At *z7+* per issue #7, solely OHM/OSM data are used.

### OHM / OSM

Ocean data are from **pure non-historical OSM** during the `import-water` stage of setup:
* `osm_ocean_polygon` and `_gen1` through `_gen4` derivatives. Used in the `water` layer to provide oceans.

Keep this, as coastline needs to be visible.

## waterway

### NaturalEarth

NaturalEarth data are used **exclusively** (no OSM) *through z8* to display waterways at large scales:
* `ne_110m_rivers_lake_centerlines`
* `ne_50m_rivers_lake_centerlines`
* `ne_10m_rivers_lake_centerlines`

At *z9+* is changes over to `osm_important_waterway_linestring` derivatives.

- [x] *TODO: Change this cutover from z7 to z6 per issue #7  May need to come up with some additional SQL to populate `osm_important_waterway_linestring_gen4` et al?*


## landcover

### NaturalEarth

NaturalEarth data are used *through z6* to display glaciers:
* `ne_110m_glaciated_areas`
* `ne_50m_glaciated_areas`
* `ne_10m_glaciated_areas`
* `ne_50m_antarctic_ice_shelves_polys`
* `ne_10m_antarctic_ice_shelves_polys`

At *z7+* these are no longer displayed, and `osm_landcover_polygon` derivatives are used instead.

- [x] *TODO: Change this cutover from z7 to z6 per issue #7  May need to come up with some additional SQL to populate `osm_landcover_polygon_gen4` et al?*


## landuse

### NaturalEarth

NaturalEarth data are used *through z8* to display urban areas:
* `ne_50m_urban_areas`
* `ne_10m_urban_areas`

At *z9+* these are no longer used, and `osm_landuse_polygon` derivatives are used instead.

- [x] *TODO: Per discussion today, see issue #12 in which remove these N.E. urban areas.*


## mountain_peak

OK. Confirmed OHM only.


## park

OK. Confirmed OHM only.


## boundary

### NaturalEarth

NaturalEarth data are brought in *through z5*:
* `ne_110m_admin_0_boundary_lines_land`
* `ne_50m_admin_1_states_provinces_lines`

At *z6+* the OSM `osm_border_linestring` derivatives are used.

### OHM / OSM

The `import-osmborder` step loads a CSV dataset in order to create the `osm_border_linestring` table and its `_gen1` through `_gen10` derivatives. This would be *non-historical OSM* data, and potentially outdated to boot. The `osm_border_linestring` tables are then used to provide the boundary layer.

Reference: https://github.com/openmaptiles/import-osmborder/blob/master/import/import_osmborder_lines.sh and https://github.com/openmaptiles/import-osmborder/releases/download/v0.4/osmborder_lines.csv.gz

Per chat today, Jeff asked that we remove the existing `boundary` data as it is not serving a purpose yet. The more complex alternative would be to modify the later stages which load the OHM PBF, to load boundary data from that PBF.

- [x] *TODO: empty existing `osm_border_linestring` tables*
- [x] *TODO: adjust OMT loading process, to create table but not load data; or else, to purge afterward*


## transportation

OK. Confirmed OHM only.


## building

OK. Confirmed OHM only.


## water_name

### NaturalEarth

NaturalEarth data are used, *but are not displayed*:
* `ne_10m_geography_marine_polys` is used to provide ranking information for `osm_marine_point`


## transportation_name

OK. Confirmed OHM only.

NaturalEarth data are used for a data-processing task, *but are not displayed*. Great Britain is pulled from the `ne_10m_admin_0_countries` table, in order to do some sort of adjustment to `omt-gb-motorway` and `omt-gb-trunk` road features.


## place

### NaturalEarth

OK. Confirmed OHM only.

NaturalEarth data are used, *but are not displayed*:
* `ne_10m_populated_places` is used to provide ranking information for `osm_city_point`
* `ne_10m_admin_1_states_provinces` is used to provide ranking information for `osm_state_point`
* `ne_10m_admin_0_countries` is used to provide ranking information for `osm_country_point`


## poi

### NaturalEarth

OK. Confirmed OHM only.

Same as with the **place** layer: NaturalEarth data are used for ranking, but not as displayed geodata.


## aeroway

OK. Confirmed OHM only.


## aerodrome_label

OK. Confirmed OHM only.

**Comment by gregallensworth** [comment]
## Boundary

* Purged the existing non-historical OSM boundary data. At *z6+* the boundaries are now absent.

https://openhistoricalmap.github.io/openhistoricaltiles/prettymap/#5.97/42.08134/-116.51183/
https://openhistoricalmap.github.io/openhistoricaltiles/prettymap/#6.50/42.08134/-116.51183/

* Added some SQL files & documentation for this sort of ad-hoc preprocessing and postprocessing

**Comment by gregallensworth** [comment]
## Landcover & Waterway

Reworked the views, so that NE is no longer used by *z6*
